# Generated by Django 5.1.4 on 2025-01-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0002_category_remove_menuitems_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='LittlelemonAPI.category'),
        ),
    ]
