# Generated by Django 5.1.4 on 2025-01-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
