# Generated by Django 5.1.5 on 2025-02-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0008_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='featured',
        ),
    ]
