# Generated by Django 5.1.5 on 2025-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0009_remove_menuitems_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='featured',
            field=models.BooleanField(db_index=True, default=1),
        ),
    ]
